#+TITLE: CMPUT201W20B2 Week 2
#+PROPERTY: header-args:C             :results output :exports both :flags -std=c99 -Wall -pedantic -Werror -g 
#+PROPERTY: header-args:sh            :results output :exports both

* Week2
** Copyright Statement

If you are in CMPUT201 at UAlberta this code is released in the public
domain to you.

Otherwise it is (c) 2020 Abram Hindle under the Apache
2 License.  Unless it is Hazel Code! Which is AGPL3.0!

*** Hazel Code is licensed under AGPL3.0+

Also found here https://github.com/hazelybell/examples/tree/C-2020-01

Hazel code is licensed: The example code is licensed under the AGPL3+ license, unless otherwise noted.

*** Apache 2 Preamble
Copyright 2020 Hazel Campbell, Abram Hindle

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
** Init ORG-MODE
;; I need this for org-mode to work well

(require 'ob-sh)
;(require 'ob-shell)
(org-babel-do-load-languages 'org-babel-load-languages '((sh . t)))
(org-babel-do-load-languages 'org-babel-load-languages '((C . t)))
(org-babel-do-load-languages 'org-babel-load-languages '((python . t)))
(setq org-src-fontify-natively t)

** Org Template
Copy and paste this to demo C

#+BEGIN_SRC C :exports both
#include <stdio.h>

int main(int argc, char**argv) {
    return 0;
}
#+END_SRC

#+RESULTS:

** Remember how to compile?

gcc -std=c99 -Wall -pedantic -Werror -o programname programname.c

** Unary versus Binary

#+BEGIN_SRC C :exports both 
#include <stdio.h>

int main() {
    int an_int = -5; // unary
    int another_int = an_int + an_int; //binary
    printf("an_int=\t%d\n", an_int);
    printf("another_int=\t%d\n", another_int);
    ++an_int;
    another_int = -(an_int) + +(an_int); //binary and unary
    printf("another_int=\t%d\n", another_int);
    another_int = -(an_int) + -(an_int); //binary and unary
    printf("another_int=\t%d\n", another_int);
    return 0;
}
#+END_SRC

#+RESULTS:
: an_int=	-5
: another_int=	-10
: another_int=	0
: another_int=	8

** Arithmetic 

Arithmetic operators have precedence. 

#+BEGIN_SRC C :exports both
#include <stdio.h>

int main() {
    int an_int = 5;
    int another_int = an_int + an_int;
    printf("another_int=%d\n", another_int);

    another_int = an_int * an_int;
    printf("(an_int*an_int) another_int=%d\n", another_int);
    int order1 = an_int * an_int + an_int * an_int / an_int;
    int order2 = (an_int * an_int) + ((an_int * an_int) / an_int);
    int order3 = an_int * (an_int + (an_int * (an_int / (an_int))));
    if ( !((order1) == order2) ) {
        printf("order1 != order2\n");
    } else {
        printf("order1 == order2\n");
    }
    if (order1 == order3) {
        printf("order1 == order3\n");
    } else {
        printf("order1 != order3\n");
    }
    
}
#+END_SRC

#+RESULTS:
: another_int=10
: (an_int*an_int) another_int=25
: order1 == order2
: order1 != order3


** Assignments in Expressions [Hazel Example]

This is a popular feature of C that causes a lot of bugs and lot of
confusion with C.

#+BEGIN_SRC C :exports both
#include <stdio.h>

int main() {
    int an_int = 5;
    printf("an_int=%d\n", an_int);
    // We can use an assignment as an expression!
    printf("(an_int = 2)=%d\n", an_int = 2);
    printf("(an_int = 5) > 5: ");
    if ((an_int = 5) > 5) {
        printf("true\n");
    } else {
        printf("false\n");
    }
    printf("(an_int *= 3) > 5: ");
    if ((an_int *=  3) > 5) {
        printf("true\n");
    } else {
        printf("false\n");
    }
    printf("an_int is now = %d\n", an_int);
    return 0;
}
#+END_SRC

#+RESULTS:
: an_int=5
: (an_int = 2)=2
: (an_int = 5) > 5: false
: (an_int *= 3) > 5: false
: an_int is now = 1

** Order of operations from Hazel

Order of operations for l-values is from right to left

#+BEGIN_SRC C :exports both :flags "-std=c99 -Wall -pedantic"
#include <stdio.h>
#include <stdlib.h>

int main() {
    int one = 1;
    int two = 2;
    int three = one = two;     // does three == one or does three == two
    printf("one=%d\n", one);
    printf("two=%d\n", two);
    printf("three=%d\n", three);
    printf("(one++)=%d (one*=2)=%d\n", one++, one *= 2);
    one = 2;
    one *= 2;
    //one++
    int tmp = one;
    one += 1;
    printf("(one++)=%d (one*=2)=%d\n", tmp, one);

    return 0;
}
#+END_SRC

#+RESULTS:
: one=2
: two=2
: three=2
: (one++)=4 (one*=2)=5

** L-value from Hazel

#+BEGIN_SRC C :exports both :flags "-std=c99 -Wall -pedantic"
#include <stdio.h>

#define N 5

int main() {
    int an_int = 5;
    printf("an_int = 5\n");
    printf("an_int=%d\n", an_int);
    an_int = 2;
    printf("an_int = 2\n");
    printf("an_int=%d\n", an_int);
    // an_int is an "lvalue"
    // aka. left value
    // anything that can appear on the left of an assignment
    // we can also use ++ and -- with lvalues
    an_int += 20;
    printf("an_int += 20\n");
    printf("an_int=%d\n", an_int);
    printf("an_int++=%d\n", an_int++);
    printf("an_int=%d\n", an_int);
    printf("++an_int=%d\n", ++an_int);
    printf("an_int=%d\n", an_int);
    an_int *= 10;
    printf("an_int *= 10\n");
    printf("an_int=%d\n", an_int);
    printf("an_int--=%d\n", an_int--);
    printf("an_int=%d\n", an_int);
    printf("--an_int=%d\n", --an_int);
    printf("an_int=%d\n", an_int);
    // None of the following work, because they are NOT lvalues!
    // 5 = 2;
    // 5 *= 10;
    // 5++;
    // N = 2;
    // N *= 10;
    // N++;
    return 0;
}
#+END_SRC

#+RESULTS:
#+begin_example
an_int = 5
an_int=5
an_int = 2
an_int=2
an_int += 20
an_int=22
an_int++=22
an_int=23
++an_int=24
an_int=24
an_int *= 10
an_int=240
an_int--=240
an_int=239
--an_int=238
an_int=238
#+end_example

** Boolean Values
C has an idea of truthy values and false values.

A 0, null, or 0.0f is a false value.

Anything else is a true value. This means that all arrays and strings
are true. All characters except \0 are true. All floating point values
that are not 0.0f or -0.0f are true.

#+BEGIN_SRC C :exports both :flags "-std=c99 -Wall -pedantic" 
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
    char chars[1024];
    char emptystring[1024] = "";
    if ( 0.0f ) {
        printf("0.0f is true!\n");
    } else {
        printf("0.0f is not true!\n");
    }
    if ( -0.0f ) {
        printf("-0.0f is true!\n");
    } else {
        printf("-0.0f is not true!\n");
    }
    if ( emptystring ) {
        printf("emptystring is true!\n");
    } else {
        printf("emptystring is not true!\n");
    }
    if ( chars ) {
        printf("character array is true!\n");
    } else {
        printf("character array is not true!\n");
    }
    if ( 0 ) {
        printf("0 is true!\n");
    } else {
        printf("0 is not true!\n");
    }
    if ( emptystring[0] ) {
        printf("emptystring[0] is true!\n");
    } else {
        printf("emptystring[0] is not true!\n");
    }
    char * nostringatall = NULL; 
    if ( nostringatall ) {
        printf("nostringatall is true!\n");
    } else {
        printf("nostringatall is not true!\n");
    }

    return 0;
}
#+END_SRC

#+RESULTS:
: 0.0f is not true!
: -0.0f is not true!
: emptystring is true!
: character array is true!
: 0 is not true!
: emptystring[0] is not true!
: nostringatall is not true!


** Boolean Values from Hazel

file:./bool.c

#+BEGIN_SRC sh :exports both   
   gcc -v -g -O0 -std=c99 -Wall -pedantic -o bool bool.c
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh :exports both :results value drawer    
  echo 2 | ./bool
#+END_SRC

#+RESULTS:
:RESULTS:
enter a number from 0-3: a is two
(a_number < 2)=0
(a_number == 2)=1
true=1
false=0
lt_two=0
(lt_two): false
lt_two_int=0
(lt_two_int): false
(1 == true): 1
(2 == true): 0
4 < a_number < 10: true
(a_number < 2 ? 111 : 222)=222
:END:


#+BEGIN_SRC C :exports both :eval no :flags "-std=c99 -Wall -pedantic" 
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
    int a_number = -1;
    printf("enter a number from 0-3: ");
    int scanf_result = scanf("%d", &a_number);
    if (scanf_result != 1) {
        printf("Error: didn't read a number!\n");
        abort();
    }
    
    if (a_number < 2) {
        printf("a less than two\n");
    } else if (a_number == 2) {
        printf("a is two\n");
    } else {
        printf("a is greater than two\n");
    }
    
    printf("(a_number < 2)=%d\n", a_number < 2);
    
    printf("(a_number == 2)=%d\n", a_number == 2);
    
    // using true and false by name: be sure to include <stdbool.h>
    printf("true=%d\n", true);
    printf("false=%d\n", false);
    
    bool lt_two = a_number < 2;
    printf("lt_two=%d\n", lt_two);
    
    printf("(lt_two): ");
    if (lt_two) {
        printf("true\n");
    } else {
        printf("false\n");
    }
    
    int lt_two_int = a_number < 2;
    printf("lt_two_int=%d\n", lt_two_int);
    
    printf("(lt_two_int): ");
    if (lt_two_int) {
        printf("true\n");
    } else {
        printf("false\n");
    }

    // NEVER do == true, because any number that's not 0 is true.
    printf("(1 == true): %d\n", 1 == true);
    printf("(2 == true): %d\n", 2 == true);
    
    
    // to fix this 4 < a && a < 10
    printf("4 < a_number < 10: ");
    if ((4 < a_number) && (a_number < 10)) {
        printf("true\n");
    } else {
        printf("false\n");
    }
    int tmp = 0;
    if (a_number < 2) {
       tmp = 111;
    } else {
       tmp = 222;
    }
    tmp = (a_number < 2 ? 111 : 222);
    a_number < 2 ? tmp = 111 : tmp = 222;
    printf("(a_number < 2 ? 111 : 222)=%d\n", tmp);
    printf("(a_number < 2 ? 111 : 222)=%d\n", (a_number < 2 ? 111 : 222));
    (a_number < 2 ? 111 :((a_number < 1)? 000 : 222));
    return 0;
}
#+END_SRC

#+RESULTS:

** Pre and Post Increment

  - x++ and ++x both eventually increment x but each does something different.

  - ++x increments x and returns x's incremented value

  - x++ returns x and then increments x's value after.

#+BEGIN_SRC C :exports both :flags "-std=c99 -Wall -pedantic"
#include <stdio.h>

int main() {
    int x = 0;
    printf("x = %d\n", x);
    printf("++x ~ %d\n", ++x);
    printf("x = %d\n", x);
    printf("x++ ~ %d\n", x++);
    printf("x = %d\n", x);
    return 0;
}
#+END_SRC

#+RESULTS:
: x = 0
: ++x ~ 1
: x = 1
: x++ ~ 1
: x = 2

*** Code for x++ and ++x 
#+BEGIN_SRC C :exports both :flags "-std=c99 -Wall -pedantic"
#include <stdio.h>

int main() {
    int x = 0;
    printf("x = %d\n", x);
    // preincrement
    // ++x;
    x = x + 1;    
    printf("++x ~ %d\n", x);
    printf("x = %d\n", x);

    // postincrement
    // x++;
    int tmp = x;
    x = x + 1;
    // note that our expression has changed from x++ to tmp because we return
    // the prior value of x and it is incremented afterwards
    printf("x++ ~ %d\n", tmp);
    printf("x = %d\n", x);
    return 0;
}
#+END_SRC

#+RESULTS:
: x = 0
: ++x ~ 1
: x = 1
: x++ ~ 1
: x = 2

file:./pre-post.c

#+BEGIN_SRC C :exports both :flags "-std=c99 -Wall -pedantic -O0 -g"
#include <stdio.h>

int main() {
    int x = 100;
    int y = x++;    
    int z = ++x;
    return y;
}
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh :exports both   
   gcc -v -g -O0 -std=c99 -Wall -pedantic -o pre-post pre-post.c
#+END_SRC

#+RESULTS:

*** Objdump it!
#+BEGIN_SRC sh :exports code :results value drawer
   gcc -v -g -O0 -std=c99 -Wall -pedantic -o pre-post pre-post.c
   objdump -d -S pre-post
#+END_SRC

#+RESULTS:
:RESULTS:

pre-post:     file format elf64-x86-64


Disassembly of section .init:

00000000000004b8 <_init>:
 4b8:	48 83 ec 08          	sub    $0x8,%rsp
 4bc:	48 8b 05 25 0b 20 00 	mov    0x200b25(%rip),%rax        # 200fe8 <__gmon_start__>
 4c3:	48 85 c0             	test   %rax,%rax
 4c6:	74 02                	je     4ca <_init+0x12>
 4c8:	ff d0                	callq  *%rax
 4ca:	48 83 c4 08          	add    $0x8,%rsp
 4ce:	c3                   	retq   

Disassembly of section .plt:

00000000000004d0 <.plt>:
 4d0:	ff 35 f2 0a 20 00    	pushq  0x200af2(%rip)        # 200fc8 <_GLOBAL_OFFSET_TABLE_+0x8>
 4d6:	ff 25 f4 0a 20 00    	jmpq   *0x200af4(%rip)        # 200fd0 <_GLOBAL_OFFSET_TABLE_+0x10>
 4dc:	0f 1f 40 00          	nopl   0x0(%rax)

Disassembly of section .plt.got:

00000000000004e0 <__cxa_finalize@plt>:
 4e0:	ff 25 12 0b 20 00    	jmpq   *0x200b12(%rip)        # 200ff8 <__cxa_finalize@GLIBC_2.2.5>
 4e6:	66 90                	xchg   %ax,%ax

Disassembly of section .text:

00000000000004f0 <_start>:
 4f0:	31 ed                	xor    %ebp,%ebp
 4f2:	49 89 d1             	mov    %rdx,%r9
 4f5:	5e                   	pop    %rsi
 4f6:	48 89 e2             	mov    %rsp,%rdx
 4f9:	48 83 e4 f0          	and    $0xfffffffffffffff0,%rsp
 4fd:	50                   	push   %rax
 4fe:	54                   	push   %rsp
 4ff:	4c 8d 05 8a 01 00 00 	lea    0x18a(%rip),%r8        # 690 <__libc_csu_fini>
 506:	48 8d 0d 13 01 00 00 	lea    0x113(%rip),%rcx        # 620 <__libc_csu_init>
 50d:	48 8d 3d e6 00 00 00 	lea    0xe6(%rip),%rdi        # 5fa <main>
 514:	ff 15 c6 0a 20 00    	callq  *0x200ac6(%rip)        # 200fe0 <__libc_start_main@GLIBC_2.2.5>
 51a:	f4                   	hlt    
 51b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000520 <deregister_tm_clones>:
 520:	48 8d 3d e9 0a 20 00 	lea    0x200ae9(%rip),%rdi        # 201010 <__TMC_END__>
 527:	55                   	push   %rbp
 528:	48 8d 05 e1 0a 20 00 	lea    0x200ae1(%rip),%rax        # 201010 <__TMC_END__>
 52f:	48 39 f8             	cmp    %rdi,%rax
 532:	48 89 e5             	mov    %rsp,%rbp
 535:	74 19                	je     550 <deregister_tm_clones+0x30>
 537:	48 8b 05 9a 0a 20 00 	mov    0x200a9a(%rip),%rax        # 200fd8 <_ITM_deregisterTMCloneTable>
 53e:	48 85 c0             	test   %rax,%rax
 541:	74 0d                	je     550 <deregister_tm_clones+0x30>
 543:	5d                   	pop    %rbp
 544:	ff e0                	jmpq   *%rax
 546:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)
 54d:	00 00 00 
 550:	5d                   	pop    %rbp
 551:	c3                   	retq   
 552:	0f 1f 40 00          	nopl   0x0(%rax)
 556:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)
 55d:	00 00 00 

0000000000000560 <register_tm_clones>:
 560:	48 8d 3d a9 0a 20 00 	lea    0x200aa9(%rip),%rdi        # 201010 <__TMC_END__>
 567:	48 8d 35 a2 0a 20 00 	lea    0x200aa2(%rip),%rsi        # 201010 <__TMC_END__>
 56e:	55                   	push   %rbp
 56f:	48 29 fe             	sub    %rdi,%rsi
 572:	48 89 e5             	mov    %rsp,%rbp
 575:	48 c1 fe 03          	sar    $0x3,%rsi
 579:	48 89 f0             	mov    %rsi,%rax
 57c:	48 c1 e8 3f          	shr    $0x3f,%rax
 580:	48 01 c6             	add    %rax,%rsi
 583:	48 d1 fe             	sar    %rsi
 586:	74 18                	je     5a0 <register_tm_clones+0x40>
 588:	48 8b 05 61 0a 20 00 	mov    0x200a61(%rip),%rax        # 200ff0 <_ITM_registerTMCloneTable>
 58f:	48 85 c0             	test   %rax,%rax
 592:	74 0c                	je     5a0 <register_tm_clones+0x40>
 594:	5d                   	pop    %rbp
 595:	ff e0                	jmpq   *%rax
 597:	66 0f 1f 84 00 00 00 	nopw   0x0(%rax,%rax,1)
 59e:	00 00 
 5a0:	5d                   	pop    %rbp
 5a1:	c3                   	retq   
 5a2:	0f 1f 40 00          	nopl   0x0(%rax)
 5a6:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)
 5ad:	00 00 00 

00000000000005b0 <__do_global_dtors_aux>:
 5b0:	80 3d 59 0a 20 00 00 	cmpb   $0x0,0x200a59(%rip)        # 201010 <__TMC_END__>
 5b7:	75 2f                	jne    5e8 <__do_global_dtors_aux+0x38>
 5b9:	48 83 3d 37 0a 20 00 	cmpq   $0x0,0x200a37(%rip)        # 200ff8 <__cxa_finalize@GLIBC_2.2.5>
 5c0:	00 
 5c1:	55                   	push   %rbp
 5c2:	48 89 e5             	mov    %rsp,%rbp
 5c5:	74 0c                	je     5d3 <__do_global_dtors_aux+0x23>
 5c7:	48 8b 3d 3a 0a 20 00 	mov    0x200a3a(%rip),%rdi        # 201008 <__dso_handle>
 5ce:	e8 0d ff ff ff       	callq  4e0 <__cxa_finalize@plt>
 5d3:	e8 48 ff ff ff       	callq  520 <deregister_tm_clones>
 5d8:	c6 05 31 0a 20 00 01 	movb   $0x1,0x200a31(%rip)        # 201010 <__TMC_END__>
 5df:	5d                   	pop    %rbp
 5e0:	c3                   	retq   
 5e1:	0f 1f 80 00 00 00 00 	nopl   0x0(%rax)
 5e8:	f3 c3                	repz retq 
 5ea:	66 0f 1f 44 00 00    	nopw   0x0(%rax,%rax,1)

00000000000005f0 <frame_dummy>:
 5f0:	55                   	push   %rbp
 5f1:	48 89 e5             	mov    %rsp,%rbp
 5f4:	5d                   	pop    %rbp
 5f5:	e9 66 ff ff ff       	jmpq   560 <register_tm_clones>

00000000000005fa <main>:
#include <stdio.h>

int main() {
 5fa:	55                   	push   %rbp
 5fb:	48 89 e5             	mov    %rsp,%rbp
    int x = 100;
 5fe:	c7 45 f4 64 00 00 00 	movl   $0x64,-0xc(%rbp)
    int y = x++;
 605:	8b 45 f4             	mov    -0xc(%rbp),%eax
 608:	8d 50 01             	lea    0x1(%rax),%edx
 60b:	89 55 f4             	mov    %edx,-0xc(%rbp)
 60e:	89 45 f8             	mov    %eax,-0x8(%rbp)
    int z = ++x;
 611:	83 45 f4 01          	addl   $0x1,-0xc(%rbp)
 615:	8b 45 f4             	mov    -0xc(%rbp),%eax
 618:	89 45 fc             	mov    %eax,-0x4(%rbp)
    return y;
 61b:	8b 45 f8             	mov    -0x8(%rbp),%eax
}
 61e:	5d                   	pop    %rbp
 61f:	c3                   	retq   

0000000000000620 <__libc_csu_init>:
 620:	41 57                	push   %r15
 622:	41 56                	push   %r14
 624:	49 89 d7             	mov    %rdx,%r15
 627:	41 55                	push   %r13
 629:	41 54                	push   %r12
 62b:	4c 8d 25 be 07 20 00 	lea    0x2007be(%rip),%r12        # 200df0 <__frame_dummy_init_array_entry>
 632:	55                   	push   %rbp
 633:	48 8d 2d be 07 20 00 	lea    0x2007be(%rip),%rbp        # 200df8 <__init_array_end>
 63a:	53                   	push   %rbx
 63b:	41 89 fd             	mov    %edi,%r13d
 63e:	49 89 f6             	mov    %rsi,%r14
 641:	4c 29 e5             	sub    %r12,%rbp
 644:	48 83 ec 08          	sub    $0x8,%rsp
 648:	48 c1 fd 03          	sar    $0x3,%rbp
 64c:	e8 67 fe ff ff       	callq  4b8 <_init>
 651:	48 85 ed             	test   %rbp,%rbp
 654:	74 20                	je     676 <__libc_csu_init+0x56>
 656:	31 db                	xor    %ebx,%ebx
 658:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
 65f:	00 
 660:	4c 89 fa             	mov    %r15,%rdx
 663:	4c 89 f6             	mov    %r14,%rsi
 666:	44 89 ef             	mov    %r13d,%edi
 669:	41 ff 14 dc          	callq  *(%r12,%rbx,8)
 66d:	48 83 c3 01          	add    $0x1,%rbx
 671:	48 39 dd             	cmp    %rbx,%rbp
 674:	75 ea                	jne    660 <__libc_csu_init+0x40>
 676:	48 83 c4 08          	add    $0x8,%rsp
 67a:	5b                   	pop    %rbx
 67b:	5d                   	pop    %rbp
 67c:	41 5c                	pop    %r12
 67e:	41 5d                	pop    %r13
 680:	41 5e                	pop    %r14
 682:	41 5f                	pop    %r15
 684:	c3                   	retq   
 685:	90                   	nop
 686:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)
 68d:	00 00 00 

0000000000000690 <__libc_csu_fini>:
 690:	f3 c3                	repz retq 

Disassembly of section .fini:

0000000000000694 <_fini>:
 694:	48 83 ec 08          	sub    $0x8,%rsp
 698:	48 83 c4 08          	add    $0x8,%rsp
 69c:	c3                   	retq   
:END:


*** Objdump Main
#+BEGIN_SRC verbatim
00000000000005fa <main>:
#include <stdio.h>

int main() {
5fa:	55                   	push   %rbp             # store main on the stack
 5fb:	48 89 e5             	mov    %rsp,%rbp        # move the stackpointer to rbp
    int x = 100;                                        
 5fe:	c7 45 f4 64 00 00 00 	movl   $0x64,-0xc(%rbp) # set x on the stack to 100
    int y = x++;
 605:	8b 45 f4             	mov    -0xc(%rbp),%eax  # copy x to eax
 608:	8d 50 01             	lea    0x1(%rax),%edx   # copy x+1 to edx (GCC why you abuse lea?!)
 60b:	89 55 f4             	mov    %edx,-0xc(%rbp)  # copy x+1 back to the stack as x
 60e:	89 45 f8             	mov    %eax,-0x8(%rbp)  # store old x from eax into where y is stored
    int z = ++x;
 611:	83 45 f4 01          	addl   $0x1,-0xc(%rbp)  # add 1 to x on the stack
 615:	8b 45 f4             	mov    -0xc(%rbp),%eax  # copy x from stack to eax
 618:	89 45 fc             	mov    %eax,-0x4(%rbp)  # store it into z
    return y;
 61b:	8b 45 f8             	mov    -0x8(%rbp),%eax  # copy y into eax to return
}
 61e:	5d                   	pop    %rbp             # restore base pointer
 61f:	c3                   	retq                    # return
#+END_SRC verbatim

** Comma Operator from Hazel

#+BEGIN_SRC C :exports both :flags "-std=c99 -Wall -pedantic"
#include <stdio.h>

/* The comma operator:
 * You should never use it in your own code!
 * It evaluates the expression on the left side of the comma, and discards the result.
 * Then it evaluates the expression on the right side. The value on the right side is the value of the expression.
 */

int main() {
    int an_int;
    int array[2] = { 100, 200 };
    // look at the inconsistency between an expression
    an_int = (1,2,3);
    printf("%d\n", an_int);
    // an a direct assignment (take the left most)
    an_int = 1,2,3;
    printf("%d\n", an_int);
    // first do (1,2) in expression order (take the right)
    // then do 2,3 in assignment order! (take the left)
    an_int = (1,2),3;
    printf("%d\n", an_int);
    printf("Don't rely on the comma operator!");
    return 0;
}
#+END_SRC

#+RESULTS:
: 3
: 1
: 2
: Don't rely on the comma operator!

** If statements

   if statements are of the form:

#+BEGIN_SRC C :eval no
   if ( condition ) {
      code for true case;
   }

   if ( condition ) {
      code for true case;
   } else {
      code for false case;
   }

   if ( condition ) {
      code for true case;
   } else if ( condition2 ) {
      code for !condition && condition2 case
   } else {
      code for false case;
   }

   &i // where my int is
   i & i // i and i
   i | i // i or i
   i ^ i // i xor i
   i && i // i logical and i
#+END_SRC


#+BEGIN_SRC C :exports both
#include <stdio.h>

int main(int argc, char**argv) {

   int input = 0;
   int condition =  input > 1;
   int condition2 = input == 1;
   int condition3 = input > 0;

   if ( condition ) {
      printf("if code for true case\n");
   }

   if ( condition ) {
      printf("if-else code for true case\n");
   } else {
      printf("if-else code for false case\n");
   }

   if ( condition ) {
      printf("if-else-if-else code for condition is true case\n");
   } else if ( condition2 ) {
      printf("if-else-if-else code for !condition && condition2 case\n");
   } else {
      printf("if-else-if-else code for !condition && !condition2 case\n");
   }

   if (condition) {
      printf("parallel-ifs condition!\n");
   }
   if (condition2) {
      printf("parallel-ifs condition2!\n");
   }
   if (condition3) {
      printf("parallel-ifs condition3!\n");
   }

    return 0;
}
#+END_SRC

#+RESULTS:
: if-else code for false case
: if-else-if-else code for !condition && !condition2 case

** Blocks! from Hazel

   Block are chunks of code that are related or grouped together by
   the parser and compiler. The code that is executed on the else
   statement of an if is a block.

   Many C statements like if do not need { } braces for blocks

#+BEGIN_SRC C :exports both :flags -std=c99
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    int some_num = 3;

    // mildly confusing syntax
    printf("Will print 0 if 0 is true:\n");
    if (0) printf("0\n");
    // printf("the real false 0\n");

    // more confusing syntax    
    printf("Will print 1 if 1 is true:\n");
    if (1)
        printf("1\n");
    printf("the real true 1\n");
    // really confusing syntax    
    if (2) printf("2 is true\n");
    else printf("2 is false\n");
    
    printf("------------------------------\n");
    
    // good syntax! Do this! Use braces!
    printf("outside of if some_num=%d\n", some_num);
    if (1) {
        int some_num = 2;
        printf("inside of if some_num=%d\n", some_num);
    }
    printf("outside of if some_num=%d\n", some_num);
    
    return 0;
}
#+END_SRC

#+RESULTS:
: Will print 0 if 0 is true:
: Will print 1 if 1 is true:
: 1
: the real true 1
: 2 is true
: ------------------------------
: outside of if some_num=3
: inside of if some_num=2
: outside of if some_num=3

   
** Ternary Statements

   An if statement that is an expression!

   ( condition ) ? ( true expression ) : ( false expression )

   Only use 1 ternary at a time. More is confusing.
   
   // don't do this
   // (condition > 0) * (true expression) + (condition == 0) * (false expression)

   int functionName(int xx) {
      int x = (xx == 0)?16:xx;
   }

#+BEGIN_SRC C :exports both
#include <stdio.h>

int main(int argc, char**argv) {
    int a_number = 0;
    int tmp = (a_number < 2 ? 111 : 222);
    // don't do this
    int res = a_number < 2 ? (tmp = 111) : (tmp = 222);
    printf("res = a_number < 2 ? tmp = 111 : tmp = 222? res = %d\n", res);
    printf("(a_number < 2 ? 111 : 222)=%d\n", tmp);
    printf("(a_number < 2 ? 111 : 222)=%d\n", (a_number < 2 ? 111 : 222));
    printf("An expression? %d\n", (a_number < 2 ? 111 :((a_number < 1)? 000 : 222)));
    return 0;
}
#+END_SRC

#+RESULTS:
: res = a_number < 2 ? tmp = 111 : tmp = 222? res = 111
: (a_number < 2 ? 111 : 222)=111
: (a_number < 2 ? 111 : 222)=111
: An expression? 111

** Switch Statements

Switch statement operators on values and matches values directly. If
you use it with strings it will surprise you and not work as expected.
Use it on characters, bools, ints. Try not to use it on floats.

#+BEGIN_SRC C :exports both
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    char direction = 'u';
    switch(direction) {
        case 'u':
        case 'U':
            printf("Up\n");
            break;
        case 'D':
            printf("Down\n");
            break;
        case 'L':
            printf("Left\n"); // bug here
        case 'R':
            printf("Right\n");
            break;
        default:
            printf("Direction is invalid");
    }
    return 0;
}
#+END_SRC

#+RESULTS:
: Up

#+BEGIN_SRC C :exports both
// Copyright (c) 2020 Hazel Campbell
// Licensed under AGPL3.0+
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    char depth = 2;
    switch(depth) {
        case 0:
            printf("0\n");
        case 1:
            printf("1111\n");
        case 2:
            printf("22222222\n");
        case 3:
            printf("333333333333\n");
        case 4:
            printf("4444444444444444\n");
            break;
        default:
            printf("Too big or too small");
    }
    return 0;
}
#+END_SRC

#+RESULTS:
: 22222222
: 333333333333
: 4444444444444444




** Switch Statements [code from Hazel]

file:./switch.c
#+BEGIN_SRC sh :exports both
   gcc -v -g -O0 -std=c99 -Wall -pedantic -o switch switch.c
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh :exports both 
   echo input  1
   echo 1 | ./switch
   echo input  2
   echo 2 | ./switch
   echo input  3
   echo 3 | ./switch
   echo input  4
   echo 4 | ./switch
   echo input  5
   echo 5 | ./switch
#+END_SRC

#+RESULTS:
#+begin_example
input 1
enter number number from 0-3: one
input 2
enter number number from 0-3: two
two or three
input 3
enter number number from 0-3: two or three
input 4
enter number number from 0-3: not a number from 0-3
input 5
enter number number from 0-3: not a number from 0-3
#+end_example



#+BEGIN_SRC C :exports both
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    int number = -1;
    printf("enter number number from 0-3: ");
    int scanned = scanf("%d", &number);
    if (scanned != 1) {
        printf("Eh?\n");
        abort();
    }
    switch(number) {
        case 0:
            printf("zero\n");
            break;
        case 1:
            printf("one\n");
            break;
        case 2:
            printf("two\n");
        case 3:
            printf("two or three\n");
            break;
        default:
            printf("not a number from 0-3\n");
    }
    return 0;
}
#+END_SRC

#+RESULTS:

** While loops
#+BEGIN_SRC C :exports both
#include <stdio.h>

int main(int argc, char**argv) {
    return 0;
}
#+END_SRC

#+RESULTS:

** For loops

#+BEGIN_SRC C :eval no :exports src

   for ( init_condition; looping_condition ; runs_each_time )

   // Loop from 0 to 10
   for ( int i = 0 ; i <= 10 ; i++ ) 
   for ( int i = 0 ; i <= 10 ; i+=1 ) 
   for ( int i = 0 ; i <= 10 ; ++i ) 

#+END_SRC

#+BEGIN_SRC C :exports both
#include <stdio.h>

int main() {
   //int i = 0;
   printf("i++\n");
   for ( int i = 0 ; i < 10 ; i++ ) {
       printf("%d ", i);
   }
   // printf("i %d", i); // i is undeclared in this scope!
   printf("\ni+=1\n");
   for ( int i = 0 ; i < 10 ; i+=1 )  {
       printf("%d ", i);
   }
   printf("\n++i\n");
   for ( int i = 0 ; i < 10 ; ++i )  {
       printf("%d ", i);
   }
   printf("\ni+=3\n");
   int i = 0;
   for ( i = 0 ; i < 10 ; i+=3 )  {
       printf("%d ", i);
   }
   printf("\ni left behind %d\n", i);
   return 0;
}
#+END_SRC

#+RESULTS:
: i++
: 0 1 2 3 4 5 6 7 8 9 
: i+=1
: 0 1 2 3 4 5 6 7 8 9 
: ++i
: 0 1 2 3 4 5 6 7 8 9 
: i+=3
: 0 3 6 9 
: i left behind 12


*** Idiomatic For Loops

Here's how you write good for loops in C99

#+BEGIN_SRC C :exports both
// Copyright (c) 2020 Hazel Campbell
// Licensed under the AGPL3.0+
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    int count_to = 4;
    // Counting from 0 to count_to-1 (3)
    for (int counter = 0; counter < count_to; counter++) {
        printf("%d ", counter);
    }
    printf("\n");
    // Counting from 1 to count_to (4)
    for (int counter = 1; counter <= count_to; counter++) {
        printf("%d ", counter);
    }
    printf("\n");
    // Counting from count_to-1 to 0
    for (int counter = count_to-1; counter >= 0; counter--) {
        printf("%d ", counter);
    }
    printf("\n");
    // Counting from count_to to 1
    for (int counter = count_to; counter >= 1; counter--) {
        printf("%d ", counter);
    }
    printf("\n");
    return 0;
}
#+END_SRC

#+RESULTS:
: 0 1 2 3 
: 1 2 3 4 
: 3 2 1 0 
: 4 3 2 1

*** Hazel's Gallery of Misfit For Loops


#+BEGIN_SRC C :exports both
// Copyright (c) 2020 Hazel Campbell
// Licensed under AGPL3.0+
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define COUNT_TO 5

int main() {
    int counter;
    // clear idiomatic for loop!
    for (counter = 0; counter < COUNT_TO; counter++) {
        printf("%d\n", counter);
    }
    printf("---\n");
    counter = 0;
    // while loop that does the same thing :/
    while (counter < COUNT_TO) {
        printf("%d\n", counter);
        counter++;
    }
    printf("---\n");
    printf("%d\n", counter);
    // for (
    //  something that runs once ;
    //  counter conditional that's checked 
    //      each time;
    //  something that happens each time ;
    // )
    printf("---\n");
    counter = 0;
    for (; counter < COUNT_TO; counter++) {
        printf("%d\n", counter);
    }
    printf("---\n");
    counter = 0;
    for (; counter < COUNT_TO; counter++) {
        printf("%d\n", counter);
        counter = COUNT_TO;
    }
    printf("---\n");
    printf("%d\n", counter);
    printf("---\n");
    counter = 0;
    for (; counter < COUNT_TO;) {
        printf("%d\n", counter);
        counter = COUNT_TO;
    }
    for (;;) {
       // infinite loop here
       break;
    }
    printf("---\n");
    printf("%d\n", counter);
    return 0;
}
#+END_SRC

#+RESULTS:
#+begin_example
0
1
2
3
4
---
0
1
2
3
4
---
5
---
0
1
2
3
4
---
0
---
6
---
0
---
5
#+end_example

** Break and For

The break statement allows you to quit the immediate for loop or while
loop you are in.

#+BEGIN_SRC C :exports both
// Copyright (c) 2020 Hazel Campbell
// Licensed under AGPL3.0+

#include <stdio.h>

int main() {
    int count_to = 4;
    for (int i = 0; i < count_to; i++) {
        for (int j = 0; j < count_to; j++) {
            if (i+j == count_to) {
                break;
            }
            printf("%d ", i+j);
        }
        printf("\n");
    }
}
#+END_SRC

#+RESULTS:
: 0 1 2 3 
: 1 2 3 
: 2 3 
: 3

*** Continue

Continue is like break except it skips the loop body to the end and
restarts.

#+BEGIN_SRC C :exports both
// Copyright (c) 2020 Hazel Campbell
// Licensed under AGPL3.0+

#include <stdio.h>

int main() {
    int count_to = 4;
    for (int i = 0; i < count_to; i++) {
        for (int j = 0; j < count_to; j++) {
            if (i+j == count_to) {
                continue;
            }
            printf("%d ", i+j);
        }
        printf("\n");
    }
}
#+END_SRC

#+RESULTS:
: 0 1 2 3 
: 1 2 3 
: 2 3 5 
: 3 5 6

** GOTO

GOTO is basically our jmp opcode from assembler except we can only go to labels.

labels in code are an identifier followed by a colon:

If you have -g flags in gcc the label will be in executable, otherwise
it will just be an offset that you jump to.

GOTOs can only be in the same function in C.

#+BEGIN_SRC C :exports both
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
    goto super;
    ala:
    printf("Aladocious\n"); 
    goto end;
    expi:
    printf("Expi\n");
    goto ala;
    fragi:
    printf("Fragilistic\n");
    goto expi;
    cali:
    printf("Cali\n");    
    goto fragi;
    super:
    printf("Super\n");    
    goto cali;
    end:
    printf("Done! Don't use GOTOs!");
}

#+END_SRC

#+RESULTS:
: Super
: Cali
: Fragilistic
: Expi
: Aladocious
: Done! Don't use GOTOs!

#+BEGIN_SRC C :exports both
// Copyright (c) 2020 Hazel Campbell
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STOP_BEFORE 7

int main() {
    for (int counter = 0; counter < STOP_BEFORE; counter++) {
        switch (counter) {
            case 0:
                printf("zero ");
                break;
            case 1:
                printf("one ");
                break;
            case 2:
                printf("two ");
                break;
            case 3:
                printf("three ");
                break;
            default:
                printf("error!\n");
                goto done;
                break;
        }
    }
    done:
    printf("\n");
    return 0;
}
#+END_SRC

#+RESULTS:
: zero one two three error!
**** Exercise

     for ( int counter = 0; counter < 60 ; counter += 3 ) { 
     for ( int counter = 1; counter < 60 ; counter *= 3 ) { 
     for ( int i = 64;  i > 0; i /= 2)  {
        printf("%d\n",i);
     }

#+BEGIN_SRC C :exports both
// Copyright (c) 2020 Hazel Campbell
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STOP_BEFORE 7

int main() {
     for ( int i = 64;  i > 0; i /= 2)  {
        printf("%d\n",i);
     }
     return 0; 
}
#+END_SRC

#+RESULTS:
: 64
: 32
: 16
: 8
: 4
: 2
: 1

** Types!

*** int!

In C ints are often 32-bit integers. They can have a sign.

#+BEGIN_SRC C :exports both
#include <stdio.h>
#include <limits.h>
int main() {
    int an_int = 6;
    printf("size_of(an_int) == %ld\n", sizeof(an_int));
    int max_int = INT_MAX;
    printf("max int == %11d\n", max_int);
    int min_int = INT_MIN;
    printf("min int == %11d\n", min_int);
    printf("an_int  == %11d \t== 0x%08x\n", an_int,  an_int);
    printf("min_int == %11d \t== 0x%08x\n", min_int, min_int);
    printf("max_int == %11d \t== 0x%08x\n", max_int, max_int);
    printf("     -1 == %11d \t== 0x%08x\n", -1,-1);
    printf("      1 == %11d \t== 0x%08x\n", 1,1);
    printf("      0 == %11d \t== 0x%08x\n", 0,0);

    return 0;
}
#+END_SRC

#+RESULTS:
: size_of(an_int) == 4
: max int ==  2147483647
: min int == -2147483648
: an_int  ==           6 	== 0x00000006
: min_int == -2147483648 	== 0x80000000
: max_int ==  2147483647 	== 0x7fffffff
:      -1 ==          -1 	== 0xffffffff
:       1 ==           1 	== 0x00000001
:       0 ==           0 	== 0x00000000

*** unsigned ints!

You can only non-negative integers if you want

#+BEGIN_SRC C :exports both
#include <stdio.h>
#include <limits.h>
int main() {
    unsigned int an_int = 6;
    printf("size_of(an_int) == %ld\n", sizeof(an_int));
    unsigned int max_int = UINT_MAX;
    printf("max int == %11u\n", max_int);
    unsigned int min_int = 0;
    printf("min int == %11u\n", min_int);
    printf("an_int  == %11u \t== 0x%08x\n", an_int,  an_int);
    printf("min_int == %11u \t== 0x%08x\n", min_int, min_int);
    printf("max_int == %11u \t== 0x%08x\n", max_int, max_int);
    printf("     -1 == %11u \t== 0x%08x\n", -1,-1);
    printf("      1 == %11u \t== 0x%08x\n", 1,1);
    printf("      0 == %11u \t== 0x%08x\n", 0,0);
    return 0;
}
#+END_SRC

#+RESULTS:
: size_of(an_int) == 4
: max int ==  4294967295
: min int ==           0
: an_int  ==           6 	== 0x00000006
: min_int ==           0 	== 0x00000000
: max_int ==  4294967295 	== 0xffffffff
:      -1 ==  4294967295 	== 0xffffffff
:       1 ==           1 	== 0x00000001
:       0 ==           0 	== 0x00000000

